get http://localhost:5000/user-api/users

###
get http://localhost:5000/usersSuggestedMaleOutfitsApi/usersSuggestedMaleOutfits/Weddings/AverageAverage/male

###
post http://localhost:5000/usersSuggestedMaleOutfitsApi/review/Weddings/AverageAverage/male/1
Content-Type: application/json

{
    "username":"maheshpothineni",
    "review":"I tried it..!! Fantastic Outfit Suggestions..thanks to O-Stylist..!!!"
}

###
get http://localhost:5000/usersSuggestedMaleOutfitsApi/review/BirthdayParties/AverageAverage/male/0

###
post http://localhost:5000/user-api/user
Content-Type: application/json

{
    "username":"Thrinath",
    "password":"22501A05E9"
}

###
post http://localhost:5000/user-api/login
Content-Type: application/json

{
    "username":"Thrinath",
    "password":"22501A05E9"
}

###
post http://localhost:5000/usersSuggestedMaleOutfitsApi/usersSuggestedMaleOutfits
Content-Type: application/json

{
    "top":"Shirt",
    "bottom":"Pant",
    "shoes":"shoes",
    "description":"description",
    "occName":"Weddings",
    "physic":"Average Average",
    "gender":"male",
    "review":[]
}

###
put http://localhost:5000/user-api/user
Content-Type: application/json

{
    "username":"ravi",
    "password":"ravi1234"
}