get https://o-stylist-6jpm.vercel.app/user-api/users

###
get https://o-stylist-6jpm.vercel.app/usersSuggestedMaleOutfitsApi/usersSuggestedMaleOutfits/ConcertsOrMusicFestivals/SkinnyAverage/male

###
post https://o-stylist-6jpm.vercel.app/usersSuggestedMaleOutfitsApi/review/Weddings/AverageAverage/male/1
Content-Type: application/json

{
    "username":"maheshpothineni",
    "review":"I tried it..!! Fantastic Outfit Suggestions..thanks to O-Stylist..!!!"
}

###
delete https://o-stylist-6jpm.vercel.app/usersSuggestedMaleOutfitsApi/review/BirthdayParties/AverageAverage/male/0/1

###
delete https://o-stylist-6jpm.vercel.app/usersSuggestedMaleOutfitsApi/usersSuggestedOutfits/BirthdayParties/AverageAverage/male/2

###
get https://o-stylist-6jpm.vercel.app/usersSuggestedMaleOutfitsApi/review/BirthdayParties/AverageAverage/male/0

###
post https://o-stylist-6jpm.vercel.app/user-api/user
Content-Type: application/json

{
    "username":"Thrinath",
    "password":"22501A05E9"
}

###
post https://o-stylist-6jpm.vercel.app/user-api/login
Content-Type: application/json

{
    "username":"Thrinath",
    "password":"22501A05E9"
}

###
post https://o-stylist-6jpm.vercel.app/usersSuggestedMaleOutfitsApi/usersSuggestedMaleOutfits
Content-Type: application/json

{
    "top":"Shirt",
    "bottom":"Pant",
    "shoes":"shoes",
    "description":"description",
    "occName":"Weddings",
    "physic":"Average Average",
    "gender":"male",
    "review":[]
}

###
put https://o-stylist-6jpm.vercel.app/user-api/user
Content-Type: application/json

{
    "username":"ravi",
    "password":"ravi1234"
}